export const state = {
  difficulty: 'easy',
  currentStage: null,
  tutStepIdx: 0,
  score: 0,
  dispCountVal: 0,
  satisfaction: 100,
  shiftElapsed: 0,
  clockMin: 8,
  clockSec: 0,
  beds: [],
  waitPatients: [],
  selectedBedId: null,
  dragPatient: null,
  selectedPatient: null,
  callTimer: null,
  panelOpen: true,
  selectedStaffId: null,
  dispTargetBedId: null,
  staffState: [],
  gameRunning: false,
  gameOver: false,
  gameClear: false,
  gamePaused: false,
  mainLoop: null,
  staffEnabled: false,
  callEnabled: false,
  satEnabled: false,
  progress: { tutDone: false, s1Done: false, s1Grade: '--', s2Done: false, s2Grade: '--' },
  orderCountForTut: 0,
  eventLog: [],
};

export const LOG_MAX = 60;
